### ISSUE TITLE
简洁的 Yaml 编写语法

### ISSUE THREAD

**Issue by PigeonYuze** [PigeonYuze/YamlBot#12]
使用现有的`yaml`来编写功能实在是太过复杂

或许我们应该有一些特殊的语法以容易地编写功能

设想：
```yaml
fn_FunctionName(arg):
 # code 
 if: true  
  switch: %call-arg%
   case:
    key1: value
    key2: value
    ELSE: ""
 try: # 使用 `try catch`语法防止`YamlBot`抛出错误
  # run
 catch: throw
# &function end

fn_callTemplate():
 # template 
 only_run: # 运行时 由此按照步骤运行
  - value.template(arg,%call-level%).moreTemplate(it)  # it 指代`value`
# &function end

fn_listener():
 createListener<MessageEvent>:
   run: # code
# &function end 
```

- [ ] function 表达式
- [ ] if-else 表达式
- [ ] switch 表达式
- [ ] try-catch 表达式
- [ ] run 表达式
- [ ] 使用`.`调用模板 表达式

工作量有点小多，就先放个预想以后再做吧

大抵等到做完监听事件后，这个功能就会提上日程吧
