### ISSUE TITLE
新增监听事件功能？

### ISSUE THREAD

**Issue by PigeonYuze** [PigeonYuze/YamlBot#16]
### 描述：
使用`YamlBot`用以监听事件

例如: 
 - 信息事件
 - 入群事件
 - 退群事件

并同时符合使用对应的生命周期 (默认使用`KotlinPlugin`)

向`Command`新增对事件的管理操作，如：
 - 关闭事件监听
 - 关闭事件`job`
 - 开启事件`job`
 - 限定事件的来源

同时每次在执行`run`时，提供对应的参数

### 预想：

新建一个配置文件`GlobalEventListener.yml`

内容如下

```yaml
listener:
 - type: "Name"
   object_bot_id: 0 # default
   filter: "%what% == %mustBe% && true || false" # default: false
   callCommand: "commandName" # default null
   $provide_event_all_value: true # default true
   priority: 'NORMAL' # default NORMAL
   read_subclass: # default [all]
    - all # 读取所有的子类
   parentScope: 'USE_EITHER_JOB$Name$' # PLUGIN_JOB | NEW_JOB_FROM_PLUGIN | USE_EITHER_JOB$Name$
   run: [

   ] # like a command
```

和`Command`原理相似

在监听事件时也会监听其子类事件

- [x] 监听事件的实现
- [x] 监听事件在`Template`上的管理操作
- [x] 在监听事件中调用

### 代办事件列表

- [x] [🚧 Add listener for bot event](https://github.com/PigeonYuze/YamlBot/commit/3e9d047e858478d7ea574ce979750404edcec842)
- [x] #22
- [x] #19
- [x] #23
- [x] #26
- [x] #25
- [x] #27
