### ISSUE TITLE
对 TOML 语法调用的支持

### ISSUE THREAD

**Issue by PigeonYuze** [PigeonYuze/YamlBot#35]
使指令注册配置文件支持 `TOML` 或者其他的配置语言

不再像 `yaml` 一样过于复杂

同时使一个 `TOML` 配置文件内可包含一个及以上的`Command`声明

### 示例样式
(声明一个`NormalCommand`)
```toml
[CommandExample]
name = ["Example"]
answeringMethod = 'QUOTE'
answeringContent = """
line 1: Hello
line 2: World
Results:
0: %call-randomResult0%
1: %call-randomResult1%
"""
condition = []

[[CommandExample.run]]
name = "randomResult0"
use = 'BASE'
call = 'random'
args = []

[[CommandExample.run]]
name = "randomResult1"
use = 'BASE'
call = 'random'
args = [100,200]
```
