### ISSUE TITLE
支持全局变量

### ISSUE THREAD

**Issue by PigeonYuze** [PigeonYuze/YamlBot#36]
支持设置全局常量，任何文件都可包含全局常量的定义。

可从任何地方调用全局常量，它看起来像`$name$`

当解析调用处时，尝试从配置下所有文件中读取`val`声明。

### 定义
声明一个映射关系，其键值为`val`

> TOML
```toml
# 于顶层定义
val.hello_world = "Hello, world!"
# 或者
[val]
hello = "Hello, "
world = "world!"
```
> YAML
```yaml
val:
  hello_world: "Hello, world!"
  hello: "Hello, "
  world: "world!"
```

### 调用
例如
```yaml
run:
 # Input your code...
- args: ['$hello_world$']  # 等同于 Hello, world!
```
